### ISSUE TITLE
Move api-gateway repository

### ISSUE THREAD

**Issue by strekm** [kyma-project/api-gateway#1]
**Description**

Move api-gateway repository from https://github.com/kyma-incubator/api-gateway.

ACs:
- [x] kyma-incubator/api-gateway deleted
- [x] api-gateway sources are in kyma-project/api-gateway
- [x] prow pipelines adjusted
- [x] necessary docu updated

**Comment by kasiakepka** [comment]
https://github.com/kyma-project/community/tree/main/docs/guidelines/repository-guidelines
