### ISSUE TITLE
ORY Oathkeeper HPA tuning

### ISSUE THREAD

**Issue by strekm** [kyma-project/api-gateway#1046]
**Description**

Remove memory metric from ORY Oathkeeper HPA conf.

**PR**

- https://github.com/kyma-project/api-gateway/pull/1053

**DoD:**
- ~~[ ] Provide unit and integration tests.~~
- [x] Provide documentation.
- [x] Verify if the solution works for both open-source Kyma and SAP BTP, Kyma runtime.
- ~~[ ] If you changed the resource limits, explain why it was needed.~~
- ~~[ ] Verify that your contributions don't decrease code coverage. If they do, explain why this is the case.~~
- [x] Add release notes.

**Attachments**

https://github.com/kyma-project/istio/blob/600154898e73494db467f9c5d9ff058dd0db58ff/internal/istiooperator/istio-operator-light.yaml#L63

**Comment by barchw** [comment]
Run the performance tests with Oathkeeper scaling based on CPU + Memory vs CPU only, no difference can be seen.

Results:
- CPU + Memory:
    - https://snapshots.raintank.io/dashboard/snapshot/mzQaXq390DzzkvU33jjLFXqp6KcNQdQi?orgId=0
    - https://snapshots.raintank.io/dashboard/snapshot/G8edG3TNneT71dVXWw9vKQ7LvoNCx5Ro?orgId=0
- CPU:
    - https://snapshots.raintank.io/dashboard/snapshot/LQAjQOrUpvzxuTkOYxt12Yc43ZnQJBHv?orgId=0
    - https://snapshots.raintank.io/dashboard/snapshot/WO4kxYzWXDX6jc83aEJH6GeDxUST4yS9?orgId=0
