### ISSUE TITLE
Error watching Ory Rules

### ISSUE THREAD

**Issue by kolodziejczak** [kyma-project/api-gateway#1047]
**Description**

![image](https://github.com/kyma-project/api-gateway/assets/69915024/8a925672-61b5-46cb-a6de-e3e68166987c)

**Expected result**

Error logs are no longer appearing

**Actual result**

Error logs appear, logging an issue with listing Ory Rules

**Steps to reproduce**

Run test-integration-gateway Makefile target, which will run Gateway integration tests suite

**Troubleshooting**

**PR**
- https://github.com/kyma-project/api-gateway/pull/1049

**Comment by barchw** [comment]
Reproduce by:
1. Install API Gateway
2. Create a Ory based API Rule (e.g. OAuth2 intro):
```yaml

**Comment by barchw** [comment]
An upstream issue exists for this: https://github.com/kubernetes-sigs/controller-runtime/issues/2723
