### ISSUE TITLE
Host link in APIRule in UI broken

### ISSUE THREAD

**Issue by gopalanand333** [kyma-project/api-gateway#1127]
When you add an APIRule that has only a short "host" defined, e.g. host: httpbin the host in the APIRule UI is broken.
The host is incorrect in the list and details view.
image
image

Expected result
The host link in the APIRule list and details is valid and doesn't contain null.

Actual result
The APIRule host link is broken.

Steps to reproduce

Apply APIRule without full host name
kubectl apply -f - <<EOF
apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: httpbin-rule
  namespace: default
  labels:
    app: httpbin
spec:
  gateway: kyma-system/kyma-gateway
  host: httpbin
  service:
    name: httpbin
    port: 8000
  rules:
    - path: /anything
      methods: [ "GET", "POST"]
      mutators: [ ]
      accessStrategies:
        - handler: no_auth
EOF
Check APIRules list and details of the APIRule

This issue was reported here: https://github.com/kyma-project/api-gateway/issues/870 and still persists

**Comment by barchw** [comment]
Hey @gopalanand333 I managed to reproduce your issue, it happens when APIRule has gateway configured in `ns/name` format. We will be providing a fix for that.

**Comment by barchw** [comment]
With today's upgrade of api-gateway in regular channel the issue should be resolved. @gopalanand333 please check if it looks OK now
