### ISSUE TITLE
bug: controller doesn't reconcile managed istio resources if they are deleted externally

### ISSUE THREAD

**Issue by Ressetkk** [kyma-project/api-gateway#1175]
/kind bug
/area api-gateway

To prevent accidental deletion or uncontrolled modification of resources created by our module (e.g. `kyma-gateway`) we should add a way to reconcile those objects.

If managed resource other than api-gateway CR is modified by external party, the controller doesn't get any event. That means state of cluster doesn't reflect the desired state of a CR, and controller doesn't return any error regarding it.

Research on possible ways to notify controller that any of the managed resources got modified

Solution 1: Add label and watch resources containing specific label. If any of the resources got changed, trigger reconciliation immediately. That also includes labeling all resources created directly by controller during CR reconciliation.
Solution 2: Reduce the time between default reconciliations
Solution 3: Utilize finalizers and handle deletion of managed resources. Additionally, the finalizer could become a trigger for reconciliation: modifying the resources that have our finalizer would trigger reconciliation that could restore the resource to a correct state

AC:
- [ ] Research on proposed solutions in terms of future-proofing, compatibility and maintainability

**Comment by strekm** [comment]
lets go with proposed solution 2: Reduce the time between default reconciliations. reduce reconcile time period to 30 minutes.
