### ISSUE TITLE
Upgrade test from version 2.3.1 to 2.4.1

### ISSUE THREAD

**Issue by strekm** [kyma-project/api-gateway#1193]
**Description**

Due to discovering bug and providing a fix for it execute manual upgrade test from version 2.3.1 directly to version 2.4.1, skipping 2.4.0 version. Upgrade should be zero downtime and should prove that conversion webhook is working. 

Test steps:
- provision production like cluster
- install api gateway module in version 2.3.1
- install old webhook service
- upgrade api gateway module to version 2.4.1
- confirm that apirule conversion works

**Reasons**

**DoD:**
- [ ] Provide unit and integration tests.
- [ ] Provide documentation.
- [ ] Verify if the solution works for both open-source Kyma and SAP BTP, Kyma runtime.
- [ ] If you changed the resource limits, explain why it was needed.
- [ ] Verify that your contributions don't decrease code coverage. If they do, explain why this is the case.
- [ ] Add release notes.

**Attachments**

https://github.com/kyma-project/api-gateway/issues/1187

**Comment by werdes72** [comment]
Tests were performed on a live gardener cluster. Zero downtime test during api-gateway upgrade from 2.3.1 to 2.4.1 has succeeded.
