### ISSUE TITLE
Namespace should be supported in APIRule service configuration

### ISSUE THREAD

**Issue by strekm** [kyma-project/api-gateway#12]
**Description**

Enhance service configuration by adding namespace field. This configuration should be possible on on root level as well as on path level. Namespace field should be optional. If no namespace is provided defaults to APIRule namespace. No new version is needed.

ACs:
- [x] namespace is optional field in service
- [x] api exposure tutorials updated
- [x] APIRule CR documentation updated
- [x] api- gateway tests updated
- [x] api-gateway component released and bumped in kyma
- [x] RN created

**Reasons**

Users should be able to expose services from multiple namespaces. 

**Attachments**
part of: https://github.com/kyma-project/kyma/issues/9936

**Comment by videlov** [comment]
**PRs**
https://github.com/kyma-project/kyma/pull/15562 (kyma-installation)
https://github.com/kyma-project/api-gateway/pull/29 (api-gateway)
