### ISSUE TITLE
Allow Kyma API rules with wildcards in the path both in single and multi-tenant mode

### ISSUE THREAD

**Issue by wogro** [kyma-project/api-gateway#1297]
**Description**
In order to selectively configure traffic to endpoints, we would like to be able to configure paths like
```
- /environments/*
- /environments/*/stores/*
```

It should also be possible to restrict the HTTP methods for endpoints, e.g. to only allow GET or allow all methods except DELETE, TRACE.
Such configuration should be possible both in single and multi-tenant mode.

This feature request is the outcome of a discussion with the security team and Kyma developers.

**Reasons**
Without the option of specifying detailed paths, malformed or fuzzing requests would hit the workload deployment directly, rather than being dropped at ingress, increasing the attack surface and DOS risk.

**DoD:**
- [ ] Provide unit and integration tests.
- [ ] Provide documentation.
- [ ] Verify if the solution works for both open-source Kyma and SAP BTP, Kyma runtime.
- [ ] If you changed the resource limits, explain why it was needed.
- [ ] Verify that your contributions don't decrease code coverage. If they do, explain why this is the case.
- [ ] Add release notes.

**Comment by strekm** [comment]
closing as https://github.com/kyma-project/api-gateway/issues/1397 is implemented and available in Kyma BTP
