### ISSUE TITLE
Automated integration test for oauth2_intro to extAuth migration

### ISSUE THREAD

**Issue by strekm** [kyma-project/api-gateway#1334]
**Description**

API Gateway module offers zero downtime migration from APIRule v1beta1 to v2alpha1. This is critical functionality helping APIRule users migrate their workloads to newer version of APIRule without experiencing any disruption. Workloads should be available also during migration. In [previous task](https://github.com/kyma-project/api-gateway/issues/1301) noop, allow, no_auth and jwt  migrations were automated. Extend mentioned test suite to implement zero downtime migration test covering oauth2_introspection to extAuth.

If workload under the test will respond with anything else than 200 test should fail.

**PR:**
- https://github.com/kyma-project/api-gateway/pull/1358

ACs:
- [x] green test checking migration from oauth2_introspection to extAuth scenario
- [x] existing test suite extended
- [x] ~~docu updated~~ (not required, we extend existing test suites that are already documented)

**Reasons**

**DoD:**
- [x] Provide documentation.
- [x] Verify that your contributions don't decrease code coverage. If they do, explain why this is the case.

**Attachments**
https://github.com/kyma-project/api-gateway/issues/1301

**Comment by mluk-sap** [comment]
Tests green:
![Image](https://github.com/user-attachments/assets/a57c5cdd-85a1-490f-8f32-229e1532940d)
