### ISSUE TITLE
Feature toggle for rate limiting

### ISSUE THREAD

**Issue by strekm** [kyma-project/api-gateway#1396]
**Description**

Introduce feature toggle mechanism that would allow to work on rate limiting epic without introducing long living dev branch or exposing half implemented functionality to end user. Feature toggle is not meant to be exposed to end user. The toggle is meant to be only used in development processes. The toggle should control only implementation related to the rate limiting story and should not affect in any way other features of API Gateway module, e.g. APIRules or Geoblocking. Feature toggle should not be released to managed Kyma offering. 

**ACs [PO]**
- [x] feature toggle is not user facing
- [x] rate limiting features must not be exposed to end user, e.g. CRDs should not be present on a cluster
- [x] rate limiting feature toggles should be separated from other API Gateway features
- [x] feature toggle must be reusable for other features, e.g. Geoblocking
- [x] if should be possible to contribute to rate limiting story w/o releasing it to managed Kyma offering

TODOs:
- [x] Add dummy rate limiting controller and CRD for prove
- [x] implement support for feature flags using build tags
- [x] implement support to exclude feature flag resources from manifest created using kustomize
~~- [ ] add GH Action job to run unit tests for rate limiting feature~~ -> superseded by following TODO
~~- [ ] add make target for testing and building rate limiting feature~~ -> superseded by following TODO
- [x] Update existing development make targets to also include new ratelimit tag

PRs:
- https://github.com/kyma-project/api-gateway/pull/1451

**Reasons**
Enable developers to incrementally contribute to rate limiting epic w/o managing long lasting dev branch

**DoD:**
- [x] Provide unit and integration tests.
~~- [ ] Provide documentation.~~
- [x] Verify if the solution works for both open-source Kyma and SAP BTP, Kyma runtime.
~~- [ ] If you changed the resource limits, explain why it was needed.~~
- [x] Verify that your contributions don't decrease code coverage. If they do, explain why this is the case.
  - Code coverage will decrease since there is new dummy code added for RateLimit API that is not tested.
~~- [ ] Add release notes.~~

**Attachments**
part of: https://github.com/kyma-project/api-gateway/issues/1365

**Comment by Ressetkk** [comment]
It's not necessary. As long as you don't serve the API, you can't use it. And for that you have field in CRD.
