### ISSUE TITLE
Clean up old Workflow runs

### ISSUE THREAD

**Issue by kolodziejczak** [kyma-project/api-gateway#1430]
**Description**

Clean up workflows that no longer exist, but are still visible in the [Actions UI](https://github.com/kyma-project/api-gateway/actions). Those workflows can be easily detected by checking if they have a link to existing yaml file.
To avoid additional work this issue might be only done after the naming convention for CICD jobs is standardized.

**Motivation**

Better visibility and up to date Actions on the UI.

**ToDo [Developer]**
- [ ] Remove workflow runs that no longer exists in the pipelines

**PRs**
- [ ] [...]()

**AC [PO]**
- [ ] Workflows that no longer exists are no longer visible in the [Actions UI](https://github.com/kyma-project/api-gateway/actions)

**Comment by Ressetkk** [comment]
done in scope of https://github.com/kyma-project/istio/issues/1069#issue-2575970611
