### ISSUE TITLE
Exposing a service without sidecar with Istio JWT handler is allowed and doesn't prompt any warning

### ISSUE THREAD

**Issue by barchw** [kyma-project/api-gateway#190]
**Description**
With migration to Istio JWT, Istio sidecar injection becomes a requirement for support of JWT based authorisation, as it is Istio sidecar that Authorization Policy is applied to. Currently creating a APIRule that exposes a service without sidecar will not prompt any warning nor will it result in error.

**Expected result**

One of the following thing will happen:
- Exposing a service without sidecar with Istio JWT results in an error of the APIRule
- A warning is prompted to user on creation of APIRule (e.g. in Busola)

**Comment by strekm** [comment]
check will be based on pod having istio-proxy container
