### ISSUE TITLE
Bump Istio client go to 1.14.3

### ISSUE THREAD

**Issue by strekm** [kyma-project/api-gateway#3]
**Is your feature request related to a problem? Please describe.**
As follow up to this ticket https://github.com/kyma-incubator/api-gateway/issues/133 the istio client-go should be updated to the current version which is used in Kyma (1.14.1 right now)

**Comment by barchw** [comment]
Istio client-go was bumped during [API-gateway multiple service](https://github.com/kyma-project/kyma/pull/15044)
