### ISSUE TITLE
Istio JWT should forward token to workload

### ISSUE THREAD

**Issue by strekm** [kyma-project/api-gateway#367]
**Description**

Configure Istio RequestAuthentication JWT rules with `forwardOriginalToken` set to `true`.

**Reasons**

providing same functionality as ORY oathkeeper

**DoD:**
- [x] provide documentation
~~- [ ] release notes and What's New updates for Kyma customers~~
- [x] provide unit tests
~~- [ ] provide integration tests~~
- [x] test on production-like environment
~~- [ ] verify resource limits~~
~~- [ ] followup issue~~
~~- [ ] create release and bump in kyma~~

**Attachments**
- [x] https://github.com/kyma-project/api-gateway/pull/375

**Comment by ptesny** [comment]
What is the `forwardOriginalToken` syntax with ORY ?

**Comment by strekm** [comment]
@ptesny it's default setting for ORY. you don't need to configure it
