### ISSUE TITLE
Methods aren't propagated to `Allow` rules

### ISSUE THREAD

**Issue by barchw** [kyma-project/api-gateway#462]
**Description**

Virtual Service http methods are only set do those configured on API Gateway startup and no override coming from APIRule is possible.

**Expected result**
The default all methods are only set if APIRule doesn't define request methods

**Actual result**
The methods in VirtualService are always set to [all available](https://github.com/kyma-project/kyma/blame/6b6195f7a354f62a28a72ff4e6b63d27e3d63c12/resources/api-gateway/values.yaml#L54)

**Steps to reproduce**
Create an APIRule that has at least one rule with handler = `Allow`

**Troubleshooting**
The configuration isn't propagated in [here](https://github.com/kyma-project/api-gateway/blob/29d8ce01f138dab173de9f729e56f5c407df8f6a/internal/processing/ory/virtual_service_processor.go#L64C8-L64C8)

**AC**
- [x] Integration tests for handlers to verify only configured methods are allowed
- [x] Restrict exposure of methods in the VirtualService
- [x] Validate that rule methods only contain valid HTTP methods
- [x] Add release notes
- [x] Verify existing configuration on clusters

**PR**
- https://github.com/kyma-project/api-gateway/pull/769

**DoD:**
- [x] Provide unit tests.
- [x] Provide integration tests.
- [x] Provide documentation.
- [x] Test on a production-like environment.
- [x] Check the outcome of all related pipelines.
- [x] As a PR reviewer, verify code coverage and evaluate if it is acceptable.

**Comment by strekm** [comment]
please check resources created for handler noop and allow. According to this bug report instead of containing only what's configured in APIRule they contain all methods.
this bug has nothing to do with CORS configuration

**Comment by strekm** [comment]
Intended functionality of this handler was simplified configuration for quickly exposing workload. This handler is Istio based but validation is oathkeeper based. Lack of documentation adds to confusion around this handler.

Provide documentation for all handlers, including allow handler. Make it clear that allow handler exposes all methods for given path.

As a follow up we will introduce new handle exposing path and methods with strict validation and clear documentation

**Comment by strekm** [comment]
follow up task can be tracked:
- https://github.com/kyma-project/api-gateway/issues/831
- https://github.com/kyma-project/api-gateway/issues/829
