### ISSUE TITLE
API Gateway module pipelines

### ISSUE THREAD

**Issue by strekm** [kyma-project/api-gateway#467]
**Description**

API Gateway is Kyma component that will become Kyma module in the future. Both API Gateway controller and manager will stay in this repository. There are existing prow based pipelines for api-gateway controller including:
- building image
- unit testing
- integration testing
- release

There's one test still being a part of kyma: upgrade test from fast integration test. Moving this test is not a part of this task.

As a part of modularisation additional pipelines are need:
- building manager image
- linting
- unit testing
- integration testing
- generating module
- releasing
- compatibility testing
- upgrade testing

Pipelines should be based on prow and GH actions. Where it is possible goats team infrastructure should be used (GCP, domain). Pipelines should invoke makefile targets, in some cases this can be mocked (return true). Mocked pipelines targets will be implemented later on with module implementation. 

ACs:
- [x] existing api-gateway controller pipelines are not affected
- [x] module required pipelines implemented
- [x] documentation created

**Reasons**

Modularisation

**DoD:**
- [x] provide documentation
~~- [ ] release notes and What's New updates for Kyma customers~~
~~- [ ] provide unit tests~~
~~- [ ] provide integration tests~~
~~- [ ] test on production-like environment~~
~~- [ ] verify resource limits~~
~~- [ ] followup issue~~
~~- [ ] create release and bump in kyma~~
~~- [ ] PR reviewer will verify code coverage and evaluate if it is acceptable~~

**Attachments**
part of https://github.com/kyma-project/api-gateway/issues/130
Istio module pipelines as reference
https://github.com/kyma-project/keda-manager/blob/main/docs/contributor/04-10-ci-cd.md

**Comment by jaroslaw-pieszka** [comment]
Building manager image (along with binary image) for Pull Requests on `mod-dev` branch introduced by https://github.com/kyma-project/test-infra/pull/8859.
Two jobs were defined:
- `pull-api-gateway-manager-build` builds binary image and pushes it to registry `europe-docker.pkg.dev/kyma-project/dev` with the image name being `api-gateway-manager:<PR-name>` 
- `pull-api-gateway-module-build` builds module OCI image and pushes it to registry `europe-docker.pkg.dev/kyma-project/dev/unsigned`, the image name is `kyma-project.io/module/api-gateway:v0.0.1-<PR-name>`

**Comment by jaroslaw-pieszka** [comment]
Unit testing and linting introduced with #510.

Added GH workflow triggered by `pull requests` on `mod-dev` branch. The workflow runs two jobs:
- lint
- unit test with coverage checking

**Comment by jaroslaw-pieszka** [comment]
Release process:

- GitHub workflow introduced with #523
- Prow `post` and `rel` jobs creating `api-gateway-manager` binary and module template - https://github.com/kyma-project/test-infra/pull/8930

**Comment by kolodziejczak** [comment]
Build:
- Prow post job which creates manager container image on mod-dev: https://github.com/kyma-project/test-infra/pull/8924
