### ISSUE TITLE
 Remove APIRule v1alpha1 types and sync CRD documentation

### ISSUE THREAD

**Issue by triffer** [kyma-project/api-gateway#489]
**Description**

The version v1alpha1 of APIRule is deprecated and we want to remove it, before we release the module. Therefore we should delete. We should also delete all the old code that was used by conversion webhook.
Additionally when generating the APIRule CRD from the go types there is a mismatch of the generated documentation. The current documentation on the CRD were copied from the [kyma-repository](https://github.com/kyma-project/kyma/blob/main/installation/resources/crds/api-gateway/apirules.gateway.crd.yaml) and should be considered the latest state. This means we have to adapt the go types, so the generation of the CRD won't display any changes.

ACs:
- [x] APIRule v1alpha1 is removed
- [x] APIRule type documentation is adapted
- [x] APIRule conversion webhook code is removed

**Attachments**

**Comment by strekm** [comment]
Kyma PR: https://github.com/kyma-project/kyma/pull/18152
API Gateway PR: https://github.com/kyma-project/api-gateway/pull/516
