### ISSUE TITLE
APIRule conversion failure for v1beta1 resource update on resources created in v1alpha1 server-side

### ISSUE THREAD

**Issue by barchw** [kyma-project/api-gateway#50]
**Description**
When APIRule was created in version `v1alpha1` with server-side apply, trying to reapply it in `v1beta1` version will result in failure. 

**Expected result**
The resource is reapplied successfully.

**Actual result**
No change is applied / request fails.

**Steps to reproduce**
1. Create APIRule in `v1alpha1` version with server-side apply
  ```bash
  kubectl apply --server-side -f apirule-v1alpha1.yaml
  ```
2. Try to update the resource with `v1beta1` version
  ```bash
  kubectl apply --server-side -f apirule-v1beta1.yaml
  ```
3. An error will occur

**Troubleshooting**
The issue seems to be caused by conversion webhook receiving a resource with `null` spec. This issue is most likely related to `kubebuilder` as it also occurs for `Cronjob` resource tutorial

**Related issues**
- https://github.com/kubernetes-sigs/controller-runtime/issues/2022

**Comment by abbi-gaurav** [comment]
The issue itself is generic, and I believe it could be applicable to version updates for any of the Kyma CRs.
However, it could be critical for any other Kyma Custom Resources and could lead to production down scenarios

**Comment by triffer** [comment]
We fixed the conversion issue in our APIRule. The bug mentioned in the related issue is still relevant, but cannot be fixed in our component.
