### ISSUE TITLE
Configure Dependabot

### ISSUE THREAD

**Issue by strekm** [kyma-project/api-gateway#56]
**Description**

Based on [example configuration for kyma](https://github.com/kyma-project/kyma/blob/main/.github/dependabot.yml) and [documentation](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates) enable go version updates. 

ACs:
- [x] dependabot yaml file created
- [x] docker and go configuration created

**Reasons**

keeping go deps up to date

**Attachments**

**Comment by triffer** [comment]
Additional Info:
* [Dependabot PR commands](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/managing-pull-requests-for-dependency-updates#managing-dependabot-pull-requests-with-comment-commands)
* [Disabling Dependabot version updates ](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates#disabling-dependabot-version-updates)
* [Allow what dependencies are updated](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#allow)
