### ISSUE TITLE
Discuss kyma-system creation and ownership

### ISSUE THREAD

**Issue by barchw** [kyma-project/api-gateway#609]
**Description**
API Gateway controller requires `kyma-system` namespace to work. Because of this reason API Gateway chart contains the namespace resource to ensure that it exists.
Discuss whether that configuration should stay, or rather the namespace should be a pre-requisite for the controller creation.

**Reasons**
Shared state of `kyma-system` namespace might require synchronisation between different Kyma modules

**DoD:**
- [ ] Check with other Kyma teams
- [ ] Provide ADR with decision

**Comment by strekm** [comment]
`kyma-system` namespace is created by Lifecycle Manager. Modules should NOT create this namespace. This namespace should not be part of module manifest.  For testing purposes `kyma-system` with Istio enabled should be created as a part of test setup.
