### ISSUE TITLE
Automated releases for api-gateway component

### ISSUE THREAD

**Issue by strekm** [kyma-project/api-gateway#7]
**Description**

Implement necessary prow pipelines related to release proces. api-gateway versioning should follow [semver](https://semver.org/). Proces of releasing new version should be as described:
- cut of branch specific for given release e.g. 1.0
- tag on branch triggers prow pipeline creating GH release and tagging api-gateway image

If patch release is needed (security fixes, bug fixes):
- create PR containing fix to release branch
- testing pipelines green
- image build and tagged
- merge PR and new image will be build 
- tag on branch triggers prow pipeline creating GH release and tagging api-gateway image
 
Pipeline implementation should be based on kyma cli release.

ACs:
- [x] image is build on merge to release branch when delivering fix to existing version, 
- [x] image is available in kyma repo and tagged
- [x] api-gateway component pipelines are executed when delivering fix to existing version
- [x] semver is followed
- [x] release branch is tagged
- [x] release branch tag triggers prow pipeline responsible for creating api-gateway release
- [x] RN are created
- [x] github release created
- [x] asset for gh release should be api-gateway image

Stretch:
- [ ] investigate branch protected tags

**Attachments**
https://github.com/kyma-project/community/blob/main/docs/guidelines/releases-guidelines/03-kyma-cli-release-process.md
https://github.com/kyma-project/test-infra/tree/main/prow/jobs/cli

**Comment by werdes72** [comment]
PR: https://github.com/kyma-project/test-infra/pull/5953
