### ISSUE TITLE
Consistent labeling

### ISSUE THREAD

**Issue by strekm** [kyma-project/api-gateway#795]
**Description**

Based on [decision](https://github.com/kyma-project/community/issues/864) implement module labeling and common labelling for all resources managed by api-gateway module.

**Clarifications**

We did align with architects and decided for the operator resources we statically `kustomize` and also dynamically (resources reconcile) apply the common k8s labels:

```
app.kubernetes.io/name: api-gateway-operator
app.kubernetes.io/instance: api-gateway-operator-default
app.kubernetes.io/version: "x.x.x"
app.kubernetes.io/component: operator
app.kubernetes.io/part-of: api-gateway
```

For all resources incl. external resources like `ory-oathkeeper` deployment and other ext. resources we only include the kyma module label:

```
kyma-project.io/module=api-gateway
```

ACs:
- [x] labels are aligned with module labeling
- [x] common labels implemented
- [x] it is possible to use label selector to filter module resources

**Reasons**

Consistent labeling

**DoD:**
~~- [ ] Create a follow-up issue.~~
- [x] Provide unit tests.
- [x] Provide integration tests.
- [x] Provide documentation.
~~- [ ] Test on a production-like environment.~~
~~- [ ] Verify if the solution works for both open-source Kyma and SAP BTP, Kyma runtime.~~
- [x] Check the outcome of all related pipelines.
~~- [ ] Verify resource limits.~~
- [x] As a PR reviewer, verify code coverage and evaluate if it is acceptable.
~~- [ ] Create a release.~~
~~- [ ] Add release notes and What's New notes for Kyma customers.~~

**Attachments**
- [x] https://github.com/kyma-project/api-gateway/pull/812
- [x] https://github.com/kyma-project/test-infra/pull/9728

**Comment by abbi-gaurav** [comment]
@strekm , please also take into account this comment: https://github.com/kyma-project/community/issues/864#issuecomment-1875068132
