### ISSUE TITLE
Performance tests for jwt handlers

### ISSUE THREAD

**Issue by strekm** [kyma-project/api-gateway#83]
**Description**

Implement, execute and document performance tests comparing jwt handler based on oathkeeper and istio.

**DoD:**
- [x] provide documentation

**Attachments**
part of: https://github.com/kyma-project/kyma/issues/12669

**Comment by strekm** [comment]
istio JWT was perf tested [here](https://github.com/kyma-project/kyma/issues/15349)

**Comment by barchw** [comment]
PR with tests results and update to k6s script: 
- https://github.tools.sap/C5325602/kyma/pull/2/files
