### ISSUE TITLE
Change private key size of the certificate of the default API Gateway to 4096 bits

### ISSUE THREAD

**Issue by TorstenD-SAP** [kyma-project/api-gateway#839]
**Description**

The size of the private key used for the default certificate (`kyma-gateway-certs`) of the default API Gateway (`kyma-gateway`) must be set to 4096bits. Atm, it defaults to the value of 2048bits.

**Reasons**

SAP Security Requirement

**DoD:**
- [x] Add release notes.

**Attachments**
- https://github.com/kyma-project/api-gateway/pull/1357

**Comment by strekm** [comment]
API Gateway module does not use cert-manager.io. instead gardener certificate management is used. atm it is not possible to configure key size but gardener guys are working on it in https://github.com/gardener/cert-management/pull/168 PR.
