### ISSUE TITLE
Proper handling of APIRule Status

### ISSUE THREAD

**Issue by strekm** [kyma-project/api-gateway#84]
**Description**

Status object of APIRule should be adapted to changes introduced by [istio based jwt handler](https://github.com/kyma-project/api-gateway/issues/34). Existing logic should take into consideration sub resources created by different handlers. Status of subresource should be added only if that subresource will be processed. 

ACs:
- [x] status of subresource is only showed if that subresource will be managed by handler
- [x] status of istio subresources (RA & AP) is only shown if FT is turned on 

**Reasons**

Introducing jwt based handler

**DoD:**
- [x] provide unit tests
- ~~followup issue~~
- [x] execute manual tests

**Attachments**
part of: https://github.com/kyma-project/api-gateway/issues/30

**PR**
- https://github.com/kyma-project/api-gateway/pull/158

**Comment by barchw** [comment]
We need to update APIRule CRD with AuthorizationPolicy and RequestAuthentication status
