### ISSUE TITLE
Fix UI tests flakiness

### ISSUE THREAD

**Issue by barchw** [kyma-project/api-gateway#898]
**Description**

UI tests are unreliable in terms of stability and often fail without any apparent reason. Additionally upstream Busola updates did break them because of wrong level of coupling, especially using wrong Cypress selectors.

**Expected result**

- Tests are reliably succeeding every time
- The coupling to Busola is limited, making sure that upstream updates will not break tests (as often)

**Additional steps**
- Running the tests periodically with the use of Kyma dashboard `Stage` or `Dev` image might allow for faster feedback regarding changes to the UI

**Comment by strekm** [comment]
- change to TS
- simplify (covering only happy & critical path)
- decouple tests

**Comment by triffer** [comment]
TODO:
- [ ] Add non-strict Typescript config and change files to TS.
- [ ] Simplify tests, by removing steps
- [ ] Make tests independent by setting up resources required by tests without the UI and before the test runs.
