### ISSUE TITLE
Review and Update API Gateway-related Content in Kyma Learning Journey

### ISSUE THREAD

**Issue by mmitoraj** [kyma-project/api-gateway#989]
**Description**

[Delivering Side-by-Side Extensibility based on SAP BTP, Kyma runtime](https://learning.sap.com/learning-journeys/deliver-side-by-side-extensibility-based-on-sap-btp-kyma-runtime) Kyma Learning Journey got outdated. Markus Haug would like to cooperate with us in updating it.

For the API Gateway module, we need to take care of the following items:

- [ ] [Using the API Gateway to Expose Services](https://learning.sap.com/learning-journeys/deliver-side-by-side-extensibility-based-on-sap-btp-kyma-runtime/using-the-api-gateway-to-expose-services_b05bfe98-e216-439d-9fa4-f0ff18f8163b
- [ ] [Exposing a Service in Kyma with API Rules](https://learning.sap.com/learning-journeys/deliver-side-by-side-extensibility-based-on-sap-btp-kyma-runtime/exposing-a-service-in-kyma-with-api-rules_deda1696-76e6-490e-bdcd-72ba26bb527b)

**Reasons**

Content update requiring cross-team collaboration.

**Attachments**

See #5292 in internal `/backlog`

**Comment by nataliasitko** [comment]
The API Gateway section has been updated.
